//! One hand-built TLH2 index, shared by the tests of all three modules.
//!
//! Hand-built rather than generated by the TypeScript builder: a test index
//! written out byte by byte is also a second, executable statement of the
//! layout — if [`crate::format`] and this file disagree, the parser tests say
//! so immediately.

use crate::format::MAGIC;

/// Two manuscripts in one CTH group, one author and one year in the pools.
///
/// `kbo 3.22` and `kbo 22.5` under `cth 1`, both by `ls` in `2021`.
pub fn build_tiny() -> Vec<u8> {
    let sigs = [b"kbo 3.22".as_slice(), b"kbo 22.5".as_slice()];
    let auth_pool = b"ls";
    let year_pool = b"2021";

    let mut sig_pool = Vec::new();
    let s0_off = 0u32;
    sig_pool.extend_from_slice(sigs[0]);
    let s1_off = sig_pool.len() as u32;
    sig_pool.extend_from_slice(sigs[1]);

    let mut buf = Vec::new();
    buf.extend_from_slice(&MAGIC.to_le_bytes());
    buf.extend_from_slice(&1u32.to_le_bytes()); // groups
    buf.extend_from_slice(&2u32.to_le_bytes()); // items
    buf.extend_from_slice(&1u32.to_le_bytes()); // auth entries
    buf.extend_from_slice(&1u32.to_le_bytes()); // year entries
    buf.extend_from_slice(&(sig_pool.len() as u32).to_le_bytes());
    buf.extend_from_slice(&(auth_pool.len() as u32).to_le_bytes());
    buf.extend_from_slice(&(year_pool.len() as u32).to_le_bytes());
    // group 0: CTH 1, two items starting at 0
    buf.extend_from_slice(&1u16.to_le_bytes());
    buf.extend_from_slice(&2u16.to_le_bytes());
    buf.extend_from_slice(&0u32.to_le_bytes());
    for (off, sig) in [(s0_off, sigs[0]), (s1_off, sigs[1])] {
        buf.extend_from_slice(&off.to_le_bytes());
        buf.push(sig.len() as u8);
        buf.push(0); // auth id
        buf.push(0); // year id
        buf.push(0); // pad
    }
    buf.extend_from_slice(&0u16.to_le_bytes());
    buf.extend_from_slice(&(auth_pool.len() as u16).to_le_bytes());
    buf.extend_from_slice(&0u16.to_le_bytes());
    buf.extend_from_slice(&(year_pool.len() as u16).to_le_bytes());
    buf.extend_from_slice(&sig_pool);
    buf.extend_from_slice(auth_pool);
    buf.extend_from_slice(year_pool);
    buf
}
