// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	corpusLocation: () => typedError<CorpusLocation, string>(__TAURI_INVOKE("corpus_location")),
	/**
	 *  Числа о пакете, который лежит по этому пути.
	 * 
	 *  Путь приходит от окна, а окно берет его из [`corpus_location`], – своей
	 *  второй догадки о том, где лежит пакет, здесь нет.
	 */
	corpusStats: (path: string) => typedError<CorpusStats, string>(__TAURI_INVOKE("corpus_stats", { path })),
	/**
	 *  Собрать корпус и сказать, что вышло.
	 * 
	 *  `local_archive` — архив, выбранный человеком; `null` означает закрепленную
	 *  запись Zenodo через кеш, то есть ровно то, что делает консольный бинарь.
	 *  Путь приходит строкой и проверяется здесь: окно файловых ручек не получает
	 *  (§3 контракта).
	 * 
	 *  Работа идет не в главном потоке. Сборка — это от шести секунд до минуты с
	 *  лишним, а команда на главном потоке заморозила бы webview и заодно все
	 *  последующие вызовы, включая отмену.
	 */
	buildCorpus: (localArchive: string | null) => typedError<BuildReport, BuildFailure>(__TAURI_INVOKE("build_corpus", { localArchive })),
	/**
	 *  Попросить текущую сборку остановиться.
	 * 
	 *  Именно попросить: отмена в ядре кооперативная и проверяется в безопасных
	 *  местах — между документами, между чанками загрузки, — а запрос метаданных
	 *  Zenodo (до десяти секунд), пересчет MD5 архива и все, что идет после начала
	 *  публикации, не прерываются вовсе. Поэтому окно после нажатия говорит
	 *  «останавливаю» и меняет это на «остановлено» только по отказу с
	 *  `cancelled` — подтверждение приходит дважды, как требует §3 контракта.
	 * 
	 *  Ничего не делает, если сборки нет: нажатие по уже закончившемуся прогону —
	 *  не ошибка.
	 */
	cancelBuild: () => __TAURI_INVOKE<void>("cancel_build"),
};

/** Events */
export const events = {
	buildProgress: makeEvent<BuildProgress>("build-progress"),
};

/* Types */
/**
 *  Почему сборка не дошла до конца.
 * 
 *  Тегированная структура, как требует §3 `docs/FRONTEND-CONTRACT.md`: вид,
 *  предложение для человека, фаза и — отдельно от всего — стоит ли предлагать
 *  повтор. Строкой это быть не может: у отказа двадцать видов, и от вида
 *  зависит, что окну делать дальше.
 * 
 *  Поля один в один повторяют `app::Failure` ядра, включая `retryable`, который
 *  там не переписан заново, а делегирован клиенту загрузки: две независимые
 *  формулировки того же правила в этом проекте уже расходились.
 */
export type BuildFailure = {
	/**  Устойчивый машинный вид: `cancelled`, `network`, `checksum`, … */
	code: string,
	/**
	 *  Фаза, на которой это случилось, — `Phase::code` ядра. `null` там, где
	 *  отказ возможен на любой.
	 */
	phase: string | null,
	/**
	 *  Одно предложение для человека. Пути файловой системы из него убраны
	 *  ядром.
	 */
	message: string,
	retryable: boolean,
	/**  Единственный исход, который не является неисправностью. */
	cancelled: boolean,
};

/**
 *  Насколько далеко зашла сборка.
 * 
 *  Одно событие на все стадии, а не по типу на каждую: окну нужно имя стадии и,
 *  где она их знает, две половины дроби. Новый показатель — поле здесь, и
 *  старое окно, которое о нем не знает, продолжает работать.
 * 
 *  **Путей не носит.** Пять вариантов `progress::Event` несут `&Path`, и по
 *  правилу рядом со [`StatsError`] им сюда нельзя: окно показывают через плечо.
 *  Из таких событий сюда доходит только имя стадии.
 */
export type BuildProgress = {
	/**  Чей это прогресс. Тот же номер приходит в [`BuildReport::job`]. */
	job: number,
	/**  На чем прогон сейчас. */
	stage: Stage,
	/**
	 *  Числитель и знаменатель, когда стадия умеет их назвать. У загрузки
	 *  знаменателя может не быть: сервер не обязан объявлять длину.
	 */
	done: number | null,
	total: number | null,
	/**
	 *  Сколько нашлось, когда это уже известно, — окно говорит числа до того,
	 *  как появится отчет.
	 */
	manuscripts: number | null,
	groups: number | null,
	/**  Предложение, когда событие несет то, что стоит показать словами. */
	note: string | null,
};

/**
 *  Что сборка дала.
 * 
 *  Числа не пересчитываются: это то, что вернул сам прогон, — `CorpusReport`
 *  ядра, переложенный во владеющий вид. Пересчет после сборки уже однажды
 *  разошелся с манифестом в этом проекте, и это отдельная строка в комментарии
 *  `app::PackageReport`.
 * 
 *  Пути здесь есть, и это не то же самое, что путь в сообщении об ошибке
 *  (правило рядом, у [`StatsError`]): показать, что собрано и где оно лежит, —
 *  и есть работа этого окна.
 */
export type BuildReport = {
	/**
	 *  Идентификатор прогона. Им же помечены события прогресса, так что окно
	 *  может отличить отчет своей сборки от чужой.
	 */
	job: number,
	package: string,
	inventory: string,
	/**
	 *  Архив, из которого собрано, когда его выбрал человек; `null`, когда
	 *  архив пришел с Zenodo через кеш.
	 */
	archive: string | null,
	documents: number,
	groups: number,
	/**  Документы, которым пришлось дать суффикс: их сиглум был уже занят. */
	disambiguated: number,
	/**
	 *  Документы, из которых убрана ссылка на таблицу стилей, которой в пакете
	 *  нет.
	 */
	stylesheet_dropped: number,
};

/**
 *  Где лежит то, что собрала консольная часть программы.
 * 
 *  Единственный источник этих путей – ядро: каталог загрузок отдает
 *  `aruna::paths`, имя пакета и имя описи объявлены там же константами.
 *  Оболочка ничего не вычисляет сама, иначе одно поведение имело бы две
 *  реализации, расходящиеся при первой же правке ядра.
 */
export type CorpusLocation = {
	downloads: string,
	package: string,
	inventory: string,
	package_exists: boolean,
	inventory_exists: boolean,
};

/**
 *  Сколько в собранном пакете рукописей и групп.
 * 
 *  Числа окно показывает как есть, поэтому здесь они уже такие, какими их надо
 *  показать: пересчета на стороне окна нет.
 */
export type CorpusStats = {
	manuscripts: number,
	groups: number,
	source: StatsSource,
	/**  Как фрагменты разложены по группам, а не только сколько их всего. */
	spread: Spread,
	/**
	 *  Что манифест насчитал о письме корпуса.
	 * 
	 *  `None`, когда числа взяты обходом каталога: эти счетчики получены при
	 *  разборе документов и по разложенному пакету не восстанавливаются.
	 *  Пустая структура из нулей соврала бы – ноль документов вне NFC и
	 *  «неизвестно, сколько их» на экране выглядят одинаково, а значат разное.
	 */
	fonts: Fonts | null,
};

/**  Что манифест насчитал о письме корпуса при разборе. */
export type Fonts = {
	/**  Документы, чей текст пришел не в нормальной форме C. */
	not_in_nfc: number,
	/**
	 *  Документы, где встречаются кодовые точки из области частного
	 *  использования.
	 */
	with_private_use: number,
	/**  Сколько таких точек различают во всем корпусе. */
	private_use_points: number,
	/**  Аномалии письма – все шесть счетчиков манифеста одним числом. */
	anomalies: number,
};

/**  Группа и ее размер. */
export type GroupSize = {
	label: string,
	fragments: number,
};

/**
 *  Разложение фрагментов по группам CTH.
 * 
 *  Два итога – сколько фрагментов и сколько групп – ничего не говорят о том,
 *  как одно распределено по другому, а распределение здесь крайне неровное:
 *  в самой большой группе больше фрагментов, чем в четырех сотнях самых
 *  маленьких вместе.
 */
export type Spread = {
	/**  Самая большая группа. `None` – в пакете нет ни одной. */
	largest: GroupSize | null,
	/**  Групп ровно с одним фрагментом. */
	singletons: number,
	/**
	 *  Фрагменты, у которых CTH нет.
	 * 
	 *  Экспорт кладет их в группу с меткой `aruna::parse::MISSING`, и метка
	 *  берется у ядра, а не пишется здесь строкой: она принадлежит разбору, и
	 *  вторая ее копия разошлась бы с первой молча.
	 */
	without_cth: number,
};

/**
 *  Стадия прогона, как ее называет провод.
 * 
 *  Перечислением, а не строкой, и это не украшение: specta выводит из него
 *  объединение литералов, а `svelte-check` по объединению проверяет, что окно
 *  разобрало все стадии. Строка позволила бы забыть одну и показать читателю
 *  пустое место — ровно тот отказ, ради которого `progress::Event` в ядре не
 *  `#[non_exhaustive]`.
 * 
 *  Имена принадлежат оболочке: по `docs/ARCHITECTURE.md` §7 события IPC — ее
 *  собственность, а не ядра. Их семнадцать против девятнадцати вариантов
 *  события, потому что две пары — объявление стадии и ее тик — это одна стадия.
 */
export type Stage = "cache-unusable" | "cached-archive-rejected" | "archive-from-cache" | "zenodo-notice" | "zenodo-unreachable" | "downloading" | "download-retrying" | "archive-kept" | "parsing" | "entries-skipped" | "indexed" | "reading-headers" | "headers-read" | "writing" | "checking-package" | "checking-published" | "previous-package-left";

/**
 *  Откуда взяты числа.
 * 
 *  Поле нужно не окну, а тому, кто разбирается в расхождении: манифест пишет
 *  экспорт ядра в тот же миг, когда пакет складывается, а обход каталога
 *  считает то, что на диске лежит сейчас. Разойтись они могут только если
 *  пакет после сборки правили руками, и тогда важно знать, какой из двух
 *  ответов получен.
 */
export type StatsSource = "manifest" | "walk";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

